---
# Install and launch a rally benchmark
- name: Install rally result directory
  file: path=/root/rally_home state=directory owner=65500

- name: Initialize database
  docker_container:
    name: "{{ 'database' | to_uuid }}"
    image: rallyforge/rally
    state: started
    volumes:
    - /root/rally_home:/home/rally
    command: rally-manage db recreate

# NOTE(msimonin): without the pause
# the file seems not to be synced in the next task.
# Relaunching the play a second time is also a possible wokaround.
- pause: seconds=1

- name: Test whether the rally deployment has been created or not
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally rally deployment list
  register: deployment

- name: Deploy discovery context
  when: "'discovery' not in deployment.stdout"
  docker_container:
    name: "{{ 'deployment' | to_uuid }}"
    image: rallyforge/rally
    state: started
    volumes:
      - /root/rally_home:/home/rally
    env: "{{ os_env }}"
    command: rally deployment create --fromenv --name=discovery

- name: Copy rally scenarios
  copy: src={{ bench.location }} dest=/root/rally_home/ owner=655500

- name: debug
  debug: msg="rally task start {{ bench.location | basename }} --task-args '{{ bench.args }}'"

# NOTE(msimonin): ansible 2.2.0 breaks the return value.
# see https://github.com/BeyondTheClouds/enos/issues/41
- name: Run rally benchmark
  docker_container:
    name: "{{ bench.location | to_uuid }}"
    image: rallyforge/rally
    state: started
    volumes:
      - /root/rally_home:/home/rally
    command: rally task start {{ bench.location | basename }} --task-args '{{ bench.args }}'
  register: docker_output

- name: Wait for the end of the test, this may take a while...
  command: "docker ps -q --filter id={{ docker_output.ansible_facts.ansible_docker_container.Id }}"
  register: finished
  until: finished.stdout == ""
  delay: 20
  retries: 10000

- name: List available rally reports
  command: docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task list --uuids-only
  register: list

# Download rally results only if there are some reports to get back
# list.stdout is composed of only one uuid
- name: Generating rally reports (html)
  command: "docker run -v /root/rally_home:/home/rally rallyforge/rally  rally task report --tasks {{ list.stdout | replace('\n', ' ') }} --out rally-{{ bench.location | basename }}-{{ ansible_date_time.epoch }}.html"
  when: list.stdout != ""

- name: Generating rally reports (json)
  command: "docker run -v /root/rally_home:/home/rally rallyforge/rally rally task results --uuid {{ list.stdout | replace('\n', ' ') }}"
  when: list.stdout != ""
  register: json_output

- name: Writing json to a file
  copy:
    content: "{{ json_output.stdout }}"
    dest: /root/rally_home/rally-{{ bench.location | basename }}-{{ ansible_date_time.epoch }}.json
  when: list.stdout != ""
  
    
